#!/usr/bin/env python3
"""
Provision SSM parameters for template-app-ecs.

⚠️  DEPRECATED: Database passwords are now auto-generated by Terraform.
    Only session_secret and anthropic_api_key need manual provisioning.
    
    See terraform/README.md for the updated setup process.

Usage:
    ./put_ssm_params.py dev
    ./put_ssm_params.py prod
"""

import sys
import boto3
from botocore.exceptions import ClientError


def put_parameter(ssm, name, value, param_type="SecureString", overwrite=False):
    """Put a parameter in SSM Parameter Store."""
    try:
        ssm.put_parameter(
            Name=name,
            Value=value,
            Type=param_type,
            Overwrite=overwrite
        )
        status = "updated" if overwrite else "created"
        print(f"✓ {status}: {name}")
    except ClientError as e:
        if e.response['Error']['Code'] == 'ParameterAlreadyExists':
            print(f"- exists: {name} (use --overwrite to update)")
        else:
            print(f"✗ error: {name} - {e}")
            raise


def main():
    if len(sys.argv) != 2 or sys.argv[1] not in ['dev', 'prod']:
        print(__doc__)
        sys.exit(1)
    
    env = sys.argv[1]
    app_name = "template-app-ecs"
    
    print("⚠️  WARNING: This script is deprecated!")
    print("    Database passwords are now auto-generated by Terraform.")
    print("    You only need to manually create session_secret and anthropic_api_key.")
    print()
    print("Recommended approach:")
    print(f"  aws ssm put-parameter --name '/{env}/{app_name}/session_secret' \\")
    print(f"    --value \"$(openssl rand -base64 32)\" --type SecureString")
    print()
    print(f"  aws ssm put-parameter --name '/{env}/{app_name}/anthropic_api_key' \\")
    print(f"    --value '<your-key>' --type SecureString")
    print()
    
    if env == "dev":
        print(f"  # For dev only (GitHub deploy key):")
        print(f"  aws ssm put-parameter --name '/{env}/{app_name}/build_ssh_key' \\")
        print(f"    --value \"$(cat deploy-key)\" --type SecureString")
        print()
    
    print("Continue with deprecated script? (y/N): ", end="")
    response = input().strip().lower()
    if response != 'y':
        print("Aborted.")
        sys.exit(0)
    
    ssm = boto3.client('ssm', region_name='us-east-1')
    
    # Define parameters (database_password is now auto-generated, but kept for backwards compatibility)
    parameters = {
        f"/{env}/{app_name}/database_password": "AUTO_GENERATED_BY_TERRAFORM",
        f"/{env}/{app_name}/session_secret": "CHANGE_ME",
        f"/{env}/{app_name}/anthropic_api_key": "CHANGE_ME",
    }
    
    # Add build SSH key for dev only
    if env == "dev":
        parameters[f"/{env}/{app_name}/build_ssh_key"] = "CHANGE_ME"
    
    print(f"Provisioning SSM parameters for {env} environment...")
    print()
    
    for name, value in parameters.items():
        put_parameter(ssm, name, value, overwrite=False)
    
    print()
    print("Done! Update placeholder values with:")
    print()
    print(f"  # Database password is auto-generated by Terraform - no action needed!")
    print(f"  aws ssm put-parameter --name '/{env}/{app_name}/session_secret' --value '<secret>' --type SecureString --overwrite")
    print(f"  aws ssm put-parameter --name '/{env}/{app_name}/anthropic_api_key' --value '<key>' --type SecureString --overwrite")
    
    if env == "dev":
        print(f"  aws ssm put-parameter --name '/{env}/{app_name}/build_ssh_key' --value \"$(cat deploy-key)\" --type SecureString --overwrite")


if __name__ == "__main__":
    main()
